DROP TABLE IF EXISTS deps_of_step;
DROP TABLE IF EXISTS recipe_step;
DROP TABLE IF EXISTS recipe_ingredient;
DROP TABLE IF EXISTS ingredient;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS recipe;
DROP TABLE IF EXISTS user_of_app;
DROP TABLE IF EXISTS recipe_type;


CREATE TABLE user_of_app
(
    user_id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username        VARCHAR(100) UNIQUE NOT NULL,
    password        VARCHAR(255)        NOT NULL,
    date_of_registr DATE                         DEFAULT CURRENT_DATE,
    birthday_date   DATE                NOT NULL,
    email           VARCHAR(100) UNIQUE NOT NULL,
    role            VARCHAR(50)         NOT NULL DEFAULT 'usr',
    is_banned       BOOL                NOT NULL DEFAULT FALSE,
    image           VARCHAR(255)        NOT NULL DEFAULT 'photo_2025-12-20_01-36-59.jpg'
);
CREATE TABLE recipe_type
(
    recipe_type_id   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_type_name VARCHAR(50) UNIQUE NOT NULL
);
CREATE TABLE recipe
(
    recipe_id        INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    creation_date    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    difficulty       VARCHAR(50),
    title            VARCHAR(150) NOT NULL,
    description      TEXT,
    user_id          INTEGER      NOT NULL,
    recipe_type_id   INTEGER      NOT NULL,
    status_of_recipe VARCHAR(50)  NOT NULL,
    image            VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user_of_app (user_id),
    FOREIGN KEY (recipe_type_id) REFERENCES recipe_type (recipe_type_id)
);
CREATE TABLE recipe_step
(
    recipe_step_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name           VARCHAR(100) NOT NULL,
    duration       INTEGER      NOT NULL, --в минутах
    type_of        VARCHAR(20) CHECK (type_of IN ('passive', 'active')),
    description    TEXT,
    recipe_id      INTEGER      NOT NULL,
    FOREIGN KEY (recipe_id) REFERENCES recipe (recipe_id) ON DELETE CASCADE
);

CREATE TABLE deps_of_step
(
    recipe_step_id INTEGER NOT NULL,
    prev_step_id   INTEGER NOT NULL,
    PRIMARY KEY (recipe_step_id, prev_step_id),
    FOREIGN KEY (recipe_step_id) REFERENCES recipe_step (recipe_step_id) ON DELETE CASCADE,
    FOREIGN KEY (prev_step_id) REFERENCES recipe_step (recipe_step_id) ON DELETE CASCADE
);

CREATE TABLE category
(
    category_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE ingredient
(
    ingredient_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(100) UNIQUE NOT NULL,
    category_id   INTEGER             NOT NULL,
    FOREIGN KEY (category_id) REFERENCES category (category_id)
);

CREATE TABLE recipe_ingredient
(
    quantity      VARCHAR(50),
    ingredient_id INTEGER NOT NULL,
    recipe_id     INTEGER NOT NULL,
    edin_izmer    VARCHAR(50),
    PRIMARY KEY (ingredient_id, recipe_id),
    FOREIGN KEY (ingredient_id) REFERENCES ingredient (ingredient_id),
    FOREIGN KEY (recipe_id) REFERENCES recipe (recipe_id) ON DELETE CASCADE
);



INSERT INTO user_of_app (username, email, password, role, birthday_date)
VALUES ('Иван Иванов', 'ivan@example.com',
        'scrypt:32768:8:1$AJZG2Lp2BHuWOeFB$1bb7ec9f936ca6a5b9c3dc7eb85d3e388ed1edbb14aaceae5fcc0648c17ffafbebda4c0eb1493db15eaec8102f7315d9a7864a38013eb38d4f5149ce75fcdb63',
        'user', '2005-07-27'),
       ('Администратор', 'admin@example.com',
        'scrypt:32768:8:1$HlgyTmwIfrAuHTUS$4012e799c38d357c145cb34d4f9ab747f67179252193885ff12043bbc2fcf895ebf9d994a319cfc74c472f52a1ca09a97aba33582370b14997fd1c010564c6ae',
        'admin', '2006-07-27');


INSERT INTO category (name)
VALUES ('Молочные продукты'),
       ('Овощи'),
       ('Мясные изделия'),
       ('Зерновые'),
       ('Приправы'),
       ('Фрукты'),
       ('Рыба и морепродукты'),
       ('Масла и жиры'),
       ('Орехи и семена'),
       ('Сладости и выпечка'),
       ('Грибы'),
       ('Бобовые'),
       ('Яйца'),
       ('Соусы и пасты'),
       ('Напитки');

INSERT INTO recipe_type (recipe_type_name)
VALUES ('основные блюда'),
       ('салаты'),
       ('десерты'),
       ('закуски'),
       ('супы'),
       ('выпечка'),
       ('завтраки'),
       ('гарниры'),
       ('соусы'),
       ('напитки'),
       ('коктейли'),
       ('смузи'),
       ('вегетарианские блюда'),
       ('веганские блюда'),
       ('постные блюда'),
       ('диетические блюда'),
       ('низкокалорийные блюда'),
       ('быстрые блюда'),
       ('праздничные блюда'),
       ('блюда на каждый день'),
       ('детское меню'),
       ('уличная еда'),
       ('домашняя кухня'),
       ('ресторанные блюда'),
       ('итальянская кухня'),
       ('французская кухня'),
       ('японская кухня'),
       ('китайская кухня'),
       ('корейская кухня'),
       ('грузинская кухня'),
       ('мексиканская кухня'),
       ('индийская кухня'),
       ('средиземноморская кухня'),
       ('русская кухня'),
       ('украинская кухня'),
       ('кавказская кухня'),
       ('блюда из мяса'),
       ('блюда из птицы'),
       ('блюда из рыбы'),
       ('морепродукты'),
       ('блюда из овощей'),
       ('блюда из грибов'),
       ('паста'),
       ('пицца'),
       ('бургеры'),
       ('сэндвичи'),
       ('каши'),
       ('запеканки'),
       ('маринады');


INSERT INTO ingredient (name, category_id)
VALUES ('Молоко', 1),
       ('Сыр', 1),
       ('Сливки', 1),
       ('Сметана', 1),
       ('Йогурт', 1),
       ('Кефир', 1),
       ('Творог', 1),
       ('Масло сливочное', 1),
       ('Помидор', 2),
       ('Огурец', 2),
       ('Картофель', 2),
       ('Лук', 2),
       ('Чеснок', 2),
       ('Морковь', 2),
       ('Болгарский перец', 2),
       ('Кабачок', 2),
       ('Баклажан', 2),
       ('Брокколи', 2),
       ('Капуста', 2),
       ('Шпинат', 2),
       ('Курица', 3),
       ('Говядина', 3),
       ('Свинина', 3),
       ('Индейка', 3),
       ('Баранина', 3),
       ('Бекон', 3),
       ('Ветчина', 3),
       ('Колбаса', 3),
       ('Макароны', 4),
       ('Рис', 4),
       ('Гречка', 4),
       ('Овсяные хлопья', 4),
       ('Пшено', 4),
       ('Булгур', 4),
       ('Кускус', 4),
       ('Мука', 4),
       ('Хлеб', 4),
       ('Соль', 5),
       ('Сахар', 5),
       ('Черный перец', 5),
       ('Паприка', 5),
       ('Корица', 5),
       ('Куркума', 5),
       ('Базилик', 5),
       ('Орегано', 5),
       ('Лавровый лист', 5),
       ('Яблоко', 6),
       ('Банан', 6),
       ('Апельсин', 6),
       ('Лимон', 6),
       ('Груша', 6),
       ('Клубника', 6),
       ('Виноград', 6),
       ('Лосось', 7),
       ('Тунец', 7),
       ('Треска', 7),
       ('Креветки', 7),
       ('Кальмары', 7),
       ('Мидии', 7),
       ('Оливковое масло', 8),
       ('Подсолнечное масло', 8),
       ('Кокосовое масло', 8),
       ('Грецкий орех', 9),
       ('Миндаль', 9),
       ('Фундук', 9),
       ('Семена подсолнечника', 9),
       ('Семена тыквы', 9),
       ('Шоколад', 10),
       ('Мед', 10),
       ('Ваниль', 10),
       ('Какао', 10),
       ('Печенье', 10),
       ('Шампиньоны', 11),
       ('Белые грибы', 11),
       ('Лисички', 11),
       ('Фасоль', 12),
       ('Чечевица', 12),
       ('Нут', 12),
       ('Горох', 12),
       ('Куриное яйцо', 13),
       ('Перепелиное яйцо', 13),
       ('Томатный соус', 14),
       ('Соевый соус', 14),
       ('Майонез', 14),
       ('Горчица', 14),
       ('Вода', 15),
       ('Молоко кокосовое', 15),
       ('Сок апельсиновый', 15);


INSERT INTO recipe (title, description, recipe_type_id, difficulty, user_id, status_of_recipe, image)
VALUES ('Паста с соусом', 'Вкусная паста с соусом и сыром', 1, 'средняя', 1, 'not_publicated', 'images (12).jpg');


INSERT INTO recipe_step (name, description, duration, type_of, recipe_id)
VALUES ('Кипятить воду', 'Налить воду в кастрюлю и довести до кипения', 10, 'passive', 1),
       ('Замесить тесто', 'Смешать ингредиенты для теста', 15, 'active', 1),
       ('Сделать соус', 'Приготовить соус из помидоров и приправ', 5, 'active', 1),
       ('Варить макароны', 'Отварить макароны до готовности', 8, 'passive', 1),
       ('Запекать', 'Положить всё в форму и запечь', 20, 'passive', 1);


INSERT INTO deps_of_step (recipe_step_id, prev_step_id)
VALUES (4, 1),
       (5, 2),
       (5, 3);


INSERT INTO recipe_ingredient (recipe_id, ingredient_id, quantity, edin_izmer)
VALUES (1, 4, '200', 'g'),
       (1, 6, '1', 'l'),
       (1, 5, '150', 'g');